// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  floating_nav: dynamic(() => import("./FloatingNav")),
  footer: dynamic(() => import("./Footer")),
  hero: dynamic(() => import("./Hero")),
  projects: dynamic(() => import("./Projects")),
};
